<div id="wrapIt">
        <div id="header">
            <div id="logo">
            </div>
            <div id="siteInfo">
            MSU Software Engineering Senior Design Project 2010
            <br />
            <div class="right">
            <div id = "home">
             <table><tr>
               <td>
                 <asp:ImageButton ID="homeIcon" runat="server" CssClass="homeIcon"
                     ImageUrl="graphics/connIcon.gif" AlternateText="Connections" ToolTip="Connections" PostBackUrl="Main.aspx"/>
               </td>
               
                <td><div class="newConnA"><a href = "Main.aspx" title="View Connections (Home)">Connections</a></div></td></tr></table></div>
                <div class="clear"></div>
            </div>
            </div>
           
        </div>
        <div id="page">
          <table id="mainTable">
            <tr>
              <td>